version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "10:00"
      timezone: America/New_York
    reviewers:
      - "Shopify/sorbet"
    labels:
      - "dependencies"
      - "ruby"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "10:00"
      timezone: America/New_York
    reviewers:
      - "Shopify/sorbet"
    labels:
      - "dependencies"
      - "gh-actions"
