# This file strictly follows the rules defined in the Ruby style guide:
#   http://shopify.github.io/ruby-style-guide/
inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
  - 'vendor/**/*'

Style/CaseEquality:
  Enabled: false
