# This file strictly follows the rules defined in the Ruby style guide:
#   http://shopify.github.io/ruby-style-guide/
inherit_gem:
  rubocop-shopify: rubocop.yml

require:
 - rubocop-sorbet

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false
  Exclude:
  - "vendor/**/*"

Gemspec/RequireMFA:
  Enabled: false

Sorbet:
  Enabled: true

Sorbet/ConstantsFromStrings:
  Enabled: false

Sorbet/FalseSigil:
  Enabled: false

Sorbet/TrueSigil:
  Enabled: true
  Include:
    - "**/*.rb"
    - "**/*.rake"

Style/CaseEquality:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
  - "spec/tapioca/**/*"
