# This file strictly follows the rules defined in the Ruby style guide:
#   http://shopify.github.io/ruby-style-guide/
inherit_from:
  - https://shopify.github.io/ruby-style-guide/rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
  - 'vendor/**/*'
  - 'lib/t.rb'

Style/CaseEquality:
  Enabled: false
