name: tapioca

type: ruby

up:
  - ruby: 2.6.5
  - bundler

commands:
  typecheck:
    aliases: [ "tc" ]
    run:     "bin/typecheck"
  console:   "bin/console"
  test:      "bin/test"
  style:     "bin/style"
  sanity:    "bin/typecheck && bin/style && bin/test"

open:
  travis: "https://travis-ci.org/Shopify/tapioca"
