name: tapioca

type: ruby

up:
  - homebrew:
    - openssl
  - ruby: 2.5.5
  - bundler

commands:
  console:
    desc: "start a console"
    run: "bin/console"
  test:
    run: "bin/test"
  style:
    run: "bin/style"
